gravity_constant 0
parameter Ciecz=1
parameter C_stale=1
parameter Ciecz_C_stale=1
constraint 1
formula: x3 = 0.0
vertices
1 0 0 0 constraint 1
2 1 0 0 constraint 1
3 1 1 0 constraint 1
4 0 1 0 constraint 1
5 0 0 1
6 1 0 1
7 1 1 1
8 0 1 1
9 -1 -1 0 fixed
10 2 -1 0 fixed
11 2 2 0 fixed
12 -1 2 0 fixed
edges
1 1 2 constraint 1 color red
2 2 3 constraint 1 color red
3 3 4 constraint 1 color red
4 4 1 constraint 1 color red
5 5 6
6 6 7
7 7 8
8 8 5
9 1 5
10 2 6
11 3 7
12 4 8
13 9 10 fixed
14 10 11 fixed
15 11 12 fixed
16 12 9 fixed
20 1 9 constraint 1
21 2 10 constraint 1
22 3 11 constraint 1
23 4 12 constraint 1
faces
1 1 2 3 4 color -1 tension Ciecz_C_stale constraint 1
2 5 6 7 8 tension Ciecz opacity 0.7
3 1 10 -5 -9 tension Ciecz opacity 0.7
4 2 11 -6 -10 tension Ciecz opacity 0.7
5 3 12 -7 -11 tension Ciecz opacity 0.7
6 4 9 -8 -12 tension Ciecz opacity 0.7
10 20 13 -21 -1 tension C_stale constraint 1
11 2 22 -14 -21 tension C_stale constraint 1
12 3 23 -15 -22 tension C_stale constraint 1
13 4 20 -16 -23 tension C_stale constraint 1
bodies
1 -1 2 3 4 5 6 volume 1 density 1
read
showq;
nazwa_pliku:="wyniki.txt";
printf "calkowita energia powierzchniowamiedzyfazowa %g\n", \
total_energy >> nazwa_pliku
 