//pending.fe

gravity_constant 0

parameter LL=1
parameter SS=1
parameter SL=1

constraint 1   
formula: x3 = 0.0

vertices
1 0 0 0 constraint 1 
2 1 0 0 constraint 1 
3 1 1 0 constraint 1
4 0 1 0 constraint 1
5 0 0 1 
6 1 0 1 
7 1 1 1 
8 0 1 1 
9 -1 -1 0 fixed
10 2 -1 0 fixed
11 2 2 0 fixed
12 -1 2 0 fixed

edges
1 1 2 constraint 1 color red
2 2 3 constraint 1 color red 
3 3 4 constraint 1 color red 
4 4 1 constraint 1 color red 
5 5 6
6 6 7 
7 7 8 
8 8 5 
9 1 5
10 2 6
11 3 7 
12 4 8
13 9 10 fixed
14 10 11 fixed 
15 11 12 fixed 
16 12 9 fixed 
20 1 9 constraint 1
21 2 10 constraint 1
22 3 11 constraint 1
23 4 12 constraint 1 

faces    
1 1 2 3 4 color -1 tension SL constraint 1
2 5 6 7 8 tension LL opacity 0.7
3 1 10 -5 -9 tension LL opacity 0.7
4 2 11 -6 -10 tension LL opacity 0.7
5 3 12 -7 -11 tension LL opacity 0.7
6 4 9 -8 -12 tension LL opacity 0.7
10 20 13 -21 -1 tension SS constraint 1
11 2 22 -14 -21 tension SS constraint 1
12 3 23 -15 -22 tension SS constraint 1
13 4 20 -16 -23 tension SS constraint 1

bodies
1 -1 2 3 4 5 6 volume 1 density 1 

read
quiet;
showq;


fname:="results.txt"
printf "total surface energy %f\n",total_energy >> fname

// Evolution with negative gravity, i.e. pendant drop
gogo4 := { G -2; ; g 50; r; g 50;  }

// Pendant drop falling off ceiling
gogo5 := { G -5;  g 20; t .05; V 5;u 5;unset vertex constraint 1; U;m 0.02;g 20;r 2;t .1;g 50;V 100;g 100; }

s
q

gogo4
pause;

gogo5 1




